baseURL: http://example.org/

defaultContentLanguage: ru
languages:
  ru:
    disabled: false
    languageCode: ru-RU
    languageDirection: ltr
    languageName: Russian
    title: Главная
    weight: 1
  en:
    disabled: false
    languageCode: en-US
    languageDirection: ltr
    languageName: English
    title: Main
    weight: 2

paginate: 4

# this is required so that Hugo will render markdown to HTML
markup:
  goldmark:
    renderer:
      unsafe: true